import Pkg

Pkg.add("Allocations")
Pkg.add("HiGHS")
Pkg.add("Gurobi")
Pkg.add("JuMP")
Pkg.add("DataFrames")
Pkg.add("CSV")
Pkg.add("BenchmarkTools")
Pkg.add("Dates")
Pkg.add("Plots")
Pkg.add("StatsBase")
Pkg.add("Distributions")
Pkg.add("Graphs")
Pkg.add("DataStructures")
Pkg.add("MathOptInterface")
Pkg.add("SpecialFunctions")
Pkg.add("DecisionTree")
Pkg.add("ScikitLearn")
Pkg.add("NearestNeighbors")
Pkg.add("MLUtils")
